Update Traditional Chinese
Traben-0/Entity_Model_Features pull request #220
Opened 2024-06-04 05:16 UTC by yichifauzi

Update some traditional chinese and merge some missing strings from en_us.json 
(still missing some translation, needs other help)

2024-06-26 16:06 UTC, notlin4 commented
我之後會重新翻譯，目前翻譯品質不太好

2024-07-19 17:26 UTC, yichifauzi commented
Just fix and update the lang file

2024-07-21 08:47 UTC, notlin4 requested changes

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
>    "entity_model_features.config.render.tooltip": "更改自訂模型部件的繪製方式，這不會影響原版模型部件。\n一般 = 正常繪製\n閃爍綠色 = 自訂部件將閃爍綠色\n輪廓 = 模型部件的輪廓將會繪製\n已停用 = 自訂模型部件將不會繪製",
```suggestion
  "entity_model_features.config.render.tooltip": "變更自訂模型部件的繪製方式，這不會影響原版模型部件。\n一般 = 正常繪製\n閃爍綠色 = 自訂部件將閃爍綠色\n輪廓 = 模型部件的輪廓將會繪製\n已停用 = 自訂模型部件將不會繪製",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.print_mode.log_jem": "未知模型 - 記錄 & .jem",
```suggestion
  "entity_model_features.config.print_mode.log_jem": "未知模型 - 記錄和 .jem",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.print_mode.all_log_jem": "所有模型 - 記錄 & .jem",
```suggestion
  "entity_model_features.config.print_mode.all_log_jem": "所有模型 - 記錄和 .jem",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
>    "entity_model_features.config.physics.2": "使用 EMF（CEM）模型",
```suggestion
  "entity_model_features.config.physics.2": "使用 EMF (CEM) 模型",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
>    "entity_model_features.config.physics": "Physics 模組修復 #1",
```suggestion
  "entity_model_features.config.physics": "Physics 模組修正 #1",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.lod.tooltip": "設定動畫開始跳幀的距離，\n降低細節層級 (LOD)，這有助於提升效能\n無 = 不跳幀\n16 = 每距離玩家 16 格就會跳過 1 個影格\n較小的數字表示跳過更多影格和獲得更多效能提升\n但當然動畫的影格率會越低，\nLOD 距離設定得越近",
我不太確定 skip frame 的中文術語什麼，先譯為「略過影格」
```suggestion
  "entity_model_features.config.lod.tooltip": "設定動畫開始略過影格的距離，\n降低細節層級 (LOD)，這有助於提升效能\n無 = 不略過影格\n16 = 每距離玩家 16 格就會跳過 1 個影格\n較小的數字表示略過更多影格和提升\n但當然動畫的影格率會越低，\nLOD 距離設定得越近",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.low_fps_lod.tooltip": "如果啟用，這將根據您的 FPS\n減少上述設定的細節層級 (LOD) 影響。\n僅在 FPS 低於 60 時適用，因為跳幀\n在較低的 FPS 下會越來越明顯",
```suggestion
  "entity_model_features.config.low_fps_lod.tooltip": "如果啟用，這將根據您的 FPS\n減少上述設定的細節層級 (LOD) 影響。\n僅在 FPS 低於 60 時適用，因為略過影格\n在較低的 FPS 下會越來越明顯",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
>    "entity_model_features.config.options": "選項與修復",
```suggestion
  "entity_model_features.config.options": "選項與修正",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.substitute_vanilla.tooltip": "EMF 將嘗試使用原版模型\n替換 .jem 模型檔案中遺失的部分",
```suggestion
  "entity_model_features.config.substitute_vanilla.tooltip": "EMF 將嘗試使用原版模型\n替換 .jem 模型檔案中遺漏的部分",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.variable_explanation.entity_variable": "實體變數以「var.<名稱>」（浮點數）或「varb.<名稱>」（布林值）的格式指定 \n\n名稱可以是任何字串，例如「var.xyz」、「var.last_rx」等。\n\n變數附加到渲染的實體，預設值為 0 或 false。\n\n實體變數可用於儲存
```suggestion
  "entity_model_features.config.variable_explanation.entity_variable": "實體變數以「var.<名稱>」（浮點數）或「varb.<名稱>」（布林值）的格式指定 \n\n名稱可以是任何字串，例如「var.xyz」、「var.last_rx」等。\n\n變數附加到繪製的實體，預設值為 0 或 false。\n\n實體變數可用於儲存影格之間的動畫資料。",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.iris_shadow_skip.tooltip": "這將使實體模型不會\n在每個影格為渲染和 Iris 陰影傳遞動畫兩次\n這應該始終保持開啟狀態，並且僅在\n將來發生 Iris API 變更的情況下才會出現"
```suggestion
  "entity_model_features.config.iris_shadow_skip.tooltip": "這將使實體模型不會\n在每個影格為繪製和 Iris 陰影傳遞動畫兩次\n這應該始終保持開啟狀態，並且僅在\n將來發生 Iris API 變更的情況下才會出現"
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.variable_explanation.render_variable": "渲染變數\n render.shadow_size\n - 實體下方陰影的大小\n render.shadow_opacity\n - 陰影的透明度\n render.shadow_offset_x, render.shadow_offset_z\n -
```suggestion
  "entity_model_features.config.variable_explanation.render_variable": "繪製變數\n render.shadow_size\n - 實體下方陰影的大小\n render.shadow_opacity\n - 陰影的透明度\n render.shadow_offset_x, render.shadow_offset_z\n - 陰影的位置\n  render.leash_offset_x, render.leash_offset_y, render.leash_offset_z\n - 拴繩連接點的位置",
```

2024-07-21 08:47 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.variable_explanation.render_variable.title": "渲染變數",
```suggestion
  "entity_model_features.config.variable_explanation.render_variable.title": "繪製變數",
```

2024-07-21 08:49 UTC, notlin4 requested changes

2024-07-21 08:49 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.large_mob_lod.tooltip": "如果啟用，這將根據生物的大小\n減少上述設定的細節層級 (LOD) 影響。\n較大型生物的跳幀現象\n將比小型生物更不明顯",
```suggestion
  "entity_model_features.config.large_mob_lod.tooltip": "如果啟用，這將根據生物的大小\n減少上述設定的細節層級 (LOD) 影響。\n較大型生物的略過影格現象\n將比小型生物更不明顯",
```

2024-07-21 08:49 UTC, notlin4 commented on common/src/main/resources/assets/entity_model_features/lang/zh_tw.json
> +  "entity_model_features.config.function_explanation.catch": "catch(x,c,id)\n將會傳回 x，但是如果 x 是 NaN 或導致其他動畫錯誤，則會改為傳回 c。\nid 是選填的，如果新增它，catch 函數將會使用此 ID 將使用 c 的原因列印到遊戲記錄檔中\n主要用於動畫除錯，如果有可能觸發此情況，您應該真正修復它。"
```suggestion
  "entity_model_features.config.function_explanation.catch": "catch(x,c,id)\n將會傳回 x，但是如果 x 是 NaN 或導致其他動畫錯誤，則會改為傳回 c。\nid 是選填的，如果新增它，catch 函數將會使用此 ID 將使用 c 的原因輸出到遊戲記錄檔中\n主要用於動畫除錯，如果有可能觸發這類情況，你應該真正修正它。",
```

2024-08-08 11:30 UTC, merged